In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('NetFlix.csv')

In [4]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
3960,s4563,TV Show,Occupied,NaN,"Henrik Mestad, Ane Dahl Torp, Ingeborga Dapkun...","Norway, Sweden",31-Dec-19,2019,TV-MA,3,"International TV Shows, TV Dramas, TV Thrillers","In the near future, Russia initiates a ""silk g..."
7580,s812,TV Show,Behind Enemy Lines,NaN,NaN,United States,15-Aug-16,2001,TV-14,1,"British TV Shows, Docuseries","After dire setbacks in 1940, Winston Churchill..."
3587,s4227,TV Show,Morphle,NaN,NaN,Netherlands,17-Dec-20,2020,TV-Y,2,"British TV Shows, Kids' TV",Little Mila turns playtime into a series of fu...
5633,s6069,TV Show,The Adventures of Sonic the Hedgehog,NaN,"Jaleel White, Long John Baldry, Garry Chalk","United States, Canada",18-Apr-18,1993,TV-Y7,1,Kids' TV,"Hyper hedgehog Sonic and his cohort Miles ""Tai..."
2385,s3145,Movie,Jem and the Holograms,Jon M. Chu,"Aubrey Peeples, Stefanie Scott, Hayley Kiyoko,...",United States,16-Apr-20,2015,PG,119,"Dramas, Music & Musicals, Sci-Fi & Fantasy",After becoming an overnight star via the inter...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [6]:
df.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [7]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

## cleaning 'director' column

In [8]:
df['director'].isnull().value_counts()

director
False    5398
True     2389
Name: count, dtype: int64

In [9]:
df['director'] = df['director'].fillna('unknown')

In [10]:
df['director'].notnull().value_counts()

director
True    7787
Name: count, dtype: int64

In [13]:
df.loc[df['director']=='unknown' , ['type','genres']]

         type                                             genres
0     TV Show  International TV Shows, TV Dramas, TV Sci-Fi &...
4     TV Show  British TV Shows, Docuseries, Science & Nature TV
10    TV Show               Anime Series, International TV Shows
15    TV Show                                           Kids' TV
17    TV Show                                           TV Shows
...       ...                                                ...
7777  TV Show  Crime TV Shows, International TV Shows, TV Dramas
7779  TV Show              TV Dramas, TV Mysteries, TV Thrillers
7780  TV Show    International TV Shows, TV Horror, TV Mysteries
7782  TV Show                 International TV Shows, Reality TV
7783  TV Show               Anime Series, International TV Shows

[2389 rows x 2 columns]

## cleaning the cast column

In [17]:
df['cast'].isnull().value_counts()

cast
False    7069
True      718
Name: count, dtype: int64

In [18]:
df['cast'].unique()

array(['João Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, Zezé Motta, Celso Frateschi',
       'Rajneesh Duggal, Adah Sharma, Indraneil Sengupta, Anjori Alagh, Rajendranath Zutshi, Vipin Sharma, Amin Hajee, Shri Vallabh Vyas',
       'Reza Rahadian, Bunga Citra Lestari, Tara Basro, Chelsea Islan',
       ...,
       'Léa Seydoux, Adèle Exarchopoulos, Salim Kechiouche, Aurélien Recoing, Catherine Salée, Benjamin Siksou, Mona Walravens, Alma Jodorowsky, Jérémie Laheurte, Anne Loiret, Benoît Pilot, Sandor Funtek, Fanny Maurin',
       'Cate Blanchett, Sally Hawkins, Alec Baldwin, Louis C.K., Bobby Cannavale, Andrew Dice Clay, Peter Sarsgaard, Michael Stuhlbarg, Tammy Blanchard, Max Casella, Alden Ehrenreich',
       'Sarah Paulson, Mark Duplass, Clu Gulager'],
      shape=(6832,), dtype=object)

In [19]:
df['cast'] = df['cast'].fillna('unknown')

In [20]:
df['cast'].notnull().sum()

np.int64(7787)

## cleaning country

In [21]:
df['country'].isnull().sum()

np.int64(507)

In [23]:
df['country'] = df['country'].fillna('unknown country')

In [24]:
df['country'].notnull().sum()

np.int64(7787)

## cleaning rating

In [25]:
df['rating'].isnull().sum()

np.int64(7)

In [26]:
df['rating'].unique()

array(['TV-MA', 'TV-PG', 'R', 'TV-G', 'PG-13', 'TV-14', 'TV-Y', 'PG',
       'TV-Y7', 'NR', 'G', 'TV-Y7-FV', nan, 'UR', 'NC-17'], dtype=object)